# **** Setting Socket tunnel ****
- name: Role ensures that the socks tunnel is setup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  roles:
    - role: ansible-role-event-socks-tunnel
- name: Checking Windows Connectivity
  hosts: all
  gather_facts: false
  ignore_errors: true
  vars:
      account_code: "{{ hostvars['localhost']['account_code'] }}"
      trans_num: "{{ hostvars['localhost']['trans_num'] }}"
  tasks:
    - name: Check Win Connectivity
      win_ping:
      register: ping_result
    - debug: msg="Unble to reach endpoint"
      when: '"unreachable" in ping_result and ping_result.unreachable'
    - debug: msg="Able to reach endpoint"
      when: '"ping" in ping_result and ping_result.ping=="pong"'
    - name: Check user password expiry.
      win_shell: net user {{ user_name }} | find "Password expires"
      register: password
      ignore_errors: true
    - debug: msg="{{password.stdout | replace('\t', '')}}"
      when: password.rc == 0
